disabled_rules:
  - line_length
  - file_length
  - function_body_length
  - todo
  - cyclomatic_complexity
  - variable_name
  - force_cast
  - nesting
  - function_parameter_count
  - force_try
  - legacy_constructor

type_body_length:
  - 480 # warning
  - 500 # error
